@include('frontend.includes.common._tpl_start')
@include('frontend.includes.common._header')
@include('dashboard.layouts.common._partial.messages')
@yield('content')
@include('frontend.includes.common._footer')
@include('frontend.includes.common._tpl_end')
